title: "Verilog Digital Clock"
description: "RTL design with Stopwatch & Alarm (ModelSim verification, Vivado synthesis on ZCU104)"
theme: jekyll-theme-cayman

# If your repo is https://github.com/<user>/<repo>
# baseurl should be "/<repo>"
baseurl: "/Verilog-Digital-Clock-with-Stopwatch-Alarm"
url: ""

markdown: kramdown

# Nice-to-have
show_downloads: false
github:
  is_project_page: true
